/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tWX8sN12yJP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export function Component() {
  return (
    <div className="flex h-screen w-full">
      <aside className="flex flex-col border-r bg-background p-4">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-medium">Channels</h2>
          <Button variant="ghost" size="icon">
            <PlusIcon className="h-5 w-5" />
          </Button>
        </div>
        <div className="mt-4 flex-1 overflow-auto">
          <div className="space-y-2">
            <Button
              variant="ghost"
              className="w-full justify-start gap-3 rounded-md px-3 py-2 text-left hover:bg-muted"
            >
              <Avatar className="h-8 w-8 bg-primary text-primary-foreground">
                <AvatarImage src="/placeholder-user.jpg" alt="Channel 1" />
                <AvatarFallback>C1</AvatarFallback>
              </Avatar>
              <div className="flex-1 truncate">
                <div className="font-medium">Channel 1</div>
                <div className="text-xs text-muted-foreground">2 new messages</div>
              </div>
              <div className="text-xs text-muted-foreground">10m</div>
            </Button>
            <Button
              variant="ghost"
              className="w-full justify-start gap-3 rounded-md px-3 py-2 text-left hover:bg-muted"
            >
              <Avatar className="h-8 w-8 bg-secondary text-secondary-foreground">
                <AvatarImage src="/placeholder-user.jpg" alt="Channel 2" />
                <AvatarFallback>C2</AvatarFallback>
              </Avatar>
              <div className="flex-1 truncate">
                <div className="font-medium">Channel 2</div>
                <div className="text-xs text-muted-foreground">No new messages</div>
              </div>
              <div className="text-xs text-muted-foreground">1h</div>
            </Button>
            <Button
              variant="ghost"
              className="w-full justify-start gap-3 rounded-md px-3 py-2 text-left hover:bg-muted"
            >
              <Avatar className="h-8 w-8 bg-accent text-accent-foreground">
                <AvatarImage src="/placeholder-user.jpg" alt="Channel 3" />
                <AvatarFallback>C3</AvatarFallback>
              </Avatar>
              <div className="flex-1 truncate">
                <div className="font-medium">Channel 3</div>
                <div className="text-xs text-muted-foreground">5 new messages</div>
              </div>
              <div className="text-xs text-muted-foreground">2h</div>
            </Button>
          </div>
        </div>
      </aside>
      <div className="flex flex-1 flex-col">
        <header className="border-b bg-background p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Avatar className="h-8 w-8 bg-primary text-primary-foreground">
                <AvatarImage src="/placeholder-user.jpg" alt="User 1" />
                <AvatarFallback>U1</AvatarFallback>
              </Avatar>
              <div>
                <div className="font-medium">User 1</div>
                <div className="text-xs text-muted-foreground">Online</div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Button variant="ghost" size="icon">
                <SearchIcon className="h-5 w-5" />
              </Button>
              <Button variant="ghost" size="icon">
                <SettingsIcon className="h-5 w-5" />
              </Button>
            </div>
          </div>
        </header>
        <div className="flex-1 overflow-auto p-4">
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <Avatar className="h-8 w-8 bg-primary text-primary-foreground">
                <AvatarImage src="/placeholder-user.jpg" alt="User 2" />
                <AvatarFallback>U2</AvatarFallback>
              </Avatar>
              <div className="flex-1">
                <div className="rounded-lg bg-muted p-3">
                  <p>Hey there! Hows it going?</p>
                </div>
                <div className="mt-1 text-xs text-muted-foreground">10:30 AM</div>
              </div>
            </div>
            <div className="flex items-start gap-3 justify-end">
              <div className="flex-1">
                <div className="rounded-lg bg-primary p-3 text-primary-foreground">
                  <p>Pretty good, thanks for asking!</p>
                </div>
                <div className="mt-1 text-right text-xs text-muted-foreground">10:31 AM</div>
              </div>
              <Avatar className="h-8 w-8 bg-secondary text-secondary-foreground">
                <AvatarImage src="/placeholder-user.jpg" alt="User 1" />
                <AvatarFallback>U1</AvatarFallback>
              </Avatar>
            </div>
            <div className="flex items-start gap-3">
              <Avatar className="h-8 w-8 bg-accent text-accent-foreground">
                <AvatarImage src="/placeholder-user.jpg" alt="User 2" />
                <AvatarFallback>U2</AvatarFallback>
              </Avatar>
              <div className="flex-1">
                <div className="rounded-lg bg-muted p-3">
                  <p>Thats great to hear! I have a question for you...</p>
                </div>
                <div className="mt-1 text-xs text-muted-foreground">10:32 AM</div>
              </div>
            </div>
          </div>
        </div>
        <div className="border-t bg-background p-4">
          <div className="flex items-center gap-3">
            <Input
              type="text"
              placeholder="Type your message..."
              className="flex-1 rounded-lg bg-muted px-3 py-2 text-sm"
            />
            <Button variant="ghost" size="icon">
              <PaperclipIcon className="h-5 w-5" />
            </Button>
            <Button className="rounded-lg px-4 py-2 text-sm font-medium">Send</Button>
          </div>
        </div>
      </div>
    </div>
  )
}

function PaperclipIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48" />
    </svg>
  )
}


function PlusIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SearchIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function SettingsIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
